language: php
php:
  - 5.5
  - 5.4
  - 5.3
before_install:
  - pear config-set auto_discover 1
  - pear install pear/PHP_CodeSniffer
  - pear install pear.phpunit.de/phpcpd
  - phpenv rehash
before_script:
  - git clone --branch=master --depth=1 --quiet git://github.com/WoltLab/WCF.git WCF
  - rm WCF/CodeSniff/WCF/Sniffs/Namespaces/ClassMustBeImportedSniff.php
  - rm WCF/CodeSniff/WCF/Sniffs/Namespaces/UseDeclarationSniff.php
  - sed -i 's/<rule ref="WCF.Namespaces.ClassMustBeImported" \/>//' WCF/CodeSniff/WCF/ruleset.xml
  - sed -i 's/<rule ref="WCF.Namespaces.UseDeclaration" \/>//' WCF/CodeSniff/WCF/ruleset.xml
script:
  - find file -type f -name '*.php' |xargs -I file php -l file
  - phpcs -p --extensions=php --standard="`pwd`/WCF/CodeSniff/WCF" file
  - phpcpd --verbose --min-lines 10 file ;  exit 0